/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "快速开始",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-111aa466",
      "path": "/"
    },
    {
      "title": "卡片组件",
      "frontmatter": {},
      "regularPath": "/componentDocs/card.html",
      "relativePath": "componentDocs/card.md",
      "key": "v-1ddd7786",
      "path": "/componentDocs/card.html",
      "headers": [
        {
          "level": 3,
          "title": "示例",
          "slug": "示例"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      "/",
      "/componentDocs/card"
    ]
  }
}