/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Lin-UI",
  "description": "",
  "base": "/Lin-UI/",
  "headTags": [],
  "pages": [
    {
      "title": "快速开始",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-111aa466",
      "path": "/"
    },
    {
      "title": "卡片组件",
      "frontmatter": {},
      "regularPath": "/componentDocs/card.html",
      "relativePath": "componentDocs/card.md",
      "key": "v-1ddd7786",
      "path": "/componentDocs/card.html",
      "headers": [
        {
          "level": 3,
          "title": "示例",
          "slug": "示例"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/Jackie-Lin/Lin-UI/tree/master"
      },
      {
        "text": "Npm",
        "link": "https://www.npmjs.com/package/lin-ui2"
      }
    ],
    "sidebar": [
      "/",
      "/componentDocs/card"
    ]
  }
}